questions =  [ //Shorter questions (not accurate).
    {"id": 0, "question": "Liberdade de mercado é a melhor forma que uma sociedade pode prosperar", "effects": {"right": 1}},
    {"id": 1, "question": "Os trabalhadores, deveriam ter controlo sobre os meios de produção.", "effects": {"right": -1}},
    {"id": 2, "question": "Toda a industria, e os bancos devem ser nacionalizados.", "effects": {"right": -1}},
    {"id": 3, "question": "Exploração dos trabalhadores tornou-se um problema menor, e por isso a regulação deve ser como tal.", "effects": {"right": 1}},
    {"id": 4, "question": "Todos nós deveriamos pagar a mesma taxa de imposto", "effects": {"right": 1}},
    {"id": 5, "question": "Por cada um de acordo com a sua abilidade, para cada um de acordo com as suas necessidades.", "effects": {"right": 1}},
    {"id": 6, "question": "Comunismo, se for bem executado pode funcionar.", "effects": {"right": -1}},
    {"id": 7, "question": "Eu suporto o SNS.", "effects": {"right": -1}},
    {"id": 8, "question": "Protecionismo (aumentar as exportações e diminuir as importações) é uma boa ideia.", "effects": {"right": -1}},
    {"id": 9, "question": "Como as empresas não podem ser confiadas, têm que ser regulamentadas.", "effects": {"right": -1}},
    {"id": 10, "question": "A única obrigação profissional do Patrão/chefe é pagar o seu subordinado todo o mês.", "effects": {"right": 1}},
    {"id": 11, "question": "A melhor forma de combater a elite é tornar-se a elite.", "effects": {"right": 1}},
    {"id": 12, "question": "Se nasces pobre, tiveste azar mas se morres pobre a culpa é tua.", "effects": {"right": 1}},
    {"id": 13, "question": "Se o estado controlar a economia, apenas deve impedir a criação de monopólios e a 'reformulação de preços'", "effects": {"right": 1}},
    {"id": 14, "question": "O terreno, não é uma mercadoria para ser vendido ou comprado.", "effects": {"right": -1}},
    {"id": 15, "question": "Devemos calar os nossos oponentes políticos, sem exceções", "effects": {"auth": 1}},
    {"id": 16, "question": "Um estado forte, não tem que ser grande. (Concorda com esta ideia?)", "effects": {"auth": -1}},
    {"id": 17, "question": "Aqueles que não se integram na nossa sociedade devem ser segregados.", "effects": {"auth": 1}},
    {"id": 18, "question": "A entrada para o nosso pais deve ser mais liberal.", "effects": {"auth": -1}},
    {"id": 19, "question": "Um estado grande, é necessário para uma nação se ergueer", "effects": {"auth": 1}},
    {"id": 20, "question": "O estado deve ter acesso ao espaço privado de cada cidadão, incluindo os emails pessoais, para existir a certeza de que a nação está livre de atos terroristas.", "effects": {"auth": 1}},
    {"id": 21, "question": "Eu suporto Organizações como a Antifa", "effects": {"auth": 1}},
    {"id": 22, "question": "Emigrantes ilegais, devem ser ejetados do pais.", "effects": {"auth": 1}},
    {"id": 23, "question": "Quanto mais pequeno o governo, mais livre serão as pessoas.", "effects": {"auth": -1}},
    {"id": 24, "question": "A obrigação das autoridades de segurança, não é proteger as pessoas, mas forçar o status-quo à força bruta.", "effects": {"auth": 1}},
    {"id": 25, "question": "O cancelamente de certas identidades, é necessário para combater o modo de pensar retrógado", "effects": {"auth": 1}},
    {"id": 26, "question": "Populismo é vital para a democracia.", "effects": {"auth": -1}},
    {"id": 27, "question": "O povo, é quem deve decidir as leis, mesmo que esteja errado.", "effects": {"auth": -1}},
    {"id": 28, "question": "O estado, não deve ter controlo, sobre o ensino", "effects": {"auth": -1}},
    {"id": 29, "question": "Pena de morte é justificavel, para certos casos", "effects": {"auth": 1}},
    {"id": 30, "question": "Idade é só um numero.", "effects": {"prog": 1}},
    {"id": 31, "question": "Pessoas deveriam venerar quem quer que seja.", "effects": {"prog": 1}},
    {"id": 32, "question": "Nudismo é perfeitamente normal.", "effects": {"prog": 1}},
    {"id": 33, "question": "Só existem 2 géneros.", "effects": {"prog": -1}},
    {"id": 34, "question": "Existe um problema com minorias etnicas", "effects": {"prog": -1}},
    {"id": 35, "question": "Nada impede um negro de ser racista", "effects": {"prog": -1}},
    {"id": 36, "question": "Ação afirmativa é ótima.", "effects": {"prog": 1}},
    {"id": 37, "question": "É natural o homem(sexo masculino) ser perverso.", "effects": {"prog": 1}},
    {"id": 38, "question": "Existe racismo estrutural.", "effects": {"prog": 1}},
    {"id": 39, "question": "Temos que matar o homem branco.", "effects": {"prog": 1}},
    {"id": 40, "question": "Um embrião não é um ser vivo, por isso pode ser descartável.", "effects": {"prog": 1}},
    {"id": 41, "question": "O aborto deve ser apenas legal em caso de gravidez etópica.", "effects": {"prog": -1}},
    {"id": 42, "question": "Homossexuais, não devem ter o direito a casar.", "effects": {"prog": -1}},
    {"id": 43, "question": "Disforia de género é uma doença mental.", "effects": {"prog": -1}},
    {"id": 44, "question": "Narcóticos, devem ser ilegalizados.", "effects": {"prog": -1}},
    {"id": 45, "question": "Pais devem ter controlo total sobre os seus filhos.", "effects": {"prog": -1}}
];

questions_longer = //Longer questions (More accurate).
[
    {"id": 0, "question": "Liberdade de mercado é a melhor forma que uma sociedade pode prosperar", "effects": {"right": 1}},
    {"id": 1, "question": "Os trabalhadores, deveriam ter controlo sobre os meios de produção.", "effects": {"right": -1}},
    {"id": 2, "question": "Toda a industria, e os bancos devem ser nacionalizados.", "effects": {"right": -1}},
    {"id": 3, "question": "Exploração dos trabalhadores tornou-se um problema menor, e por isso a regulação deve ser como tal.", "effects": {"right": 1}},
    {"id": 4, "question": "Todos nós deveriamos pagar a mesma taxa de imposto", "effects": {"right": 1}},
    {"id": 5, "question": "Por cada um de acordo com a sua abilidade, para cada um de acordo com as suas necessidades.", "effects": {"right": 1}},
    {"id": 6, "question": "Comunismo, se for bem executado pode funcionar.", "effects": {"right": -1}},
    {"id": 7, "question": "Eu suporto o SNS.", "effects": {"right": -1}},
    {"id": 8, "question": "Protecionismo (aumentar as exportações e diminuir as importações) é uma boa ideia.", "effects": {"right": -1}},
    {"id": 9, "question": "Como as empresas não podem ser confiadas, têm que ser regulamentadas.", "effects": {"right": -1}},
    {"id": 10, "question": "A única obrigação profissional do Patrão/chefe é pagar o seu subordinado todo o mês.", "effects": {"right": 1}},
    {"id": 11, "question": "A melhor forma de combater a elite é tornar-se a elite.", "effects": {"right": 1}},
    {"id": 12, "question": "Se nasces pobre, tiveste azar mas se morres pobre a culpa é tua.", "effects": {"right": 1}},
    {"id": 13, "question": "Se o estado controlar a economia, apenas deve impedir a criação de monopólios e a 'reformulação de preços'", "effects": {"right": 1}},
    {"id": 14, "question": "O terreno, não é uma mercadoria para ser vendido ou comprado.", "effects": {"right": -1}},
    {"id": 15, "question": "Devemos calar os nossos oponentes políticos, sem exceções", "effects": {"auth": 1}},
    {"id": 16, "question": "Um estado forte, não tem que ser grande. (Concorda com esta ideia?)", "effects": {"auth": -1}},
    {"id": 17, "question": "Aqueles que não se integram na nossa sociedade devem ser segregados.", "effects": {"auth": 1}},
    {"id": 18, "question": "A entrada para o nosso pais deve ser mais liberal.", "effects": {"auth": -1}},
    {"id": 19, "question": "Um estado grande, é necessário para uma nação se ergueer", "effects": {"auth": 1}},
    {"id": 20, "question": "O estado deve ter acesso ao espaço privado de cada cidadão, incluindo os emails pessoais, para existir a certeza de que a nação está livre de atos terroristas.", "effects": {"auth": 1}},
    {"id": 21, "question": "Eu suporto Organizações como a Antifa", "effects": {"auth": 1}},
    {"id": 22, "question": "Emigrantes ilegais, devem ser ejetados do pais.", "effects": {"auth": 1}},
    {"id": 23, "question": "Quanto mais pequeno o governo, mais livre serão as pessoas.", "effects": {"auth": -1}},
    {"id": 24, "question": "A obrigação das autoridades de segurança, não é proteger as pessoas, mas forçar o status-quo à força bruta.", "effects": {"auth": 1}},
    {"id": 25, "question": "O cancelamente de certas identidades, é necessário para combater o modo de pensar retrógado", "effects": {"auth": 1}},
    {"id": 26, "question": "Populismo é vital para a democracia.", "effects": {"auth": -1}},
    {"id": 27, "question": "O povo, é quem deve decidir as leis, mesmo que esteja errado.", "effects": {"auth": -1}},
    {"id": 28, "question": "O estado, não deve ter controlo, sobre o ensino", "effects": {"auth": -1}},
    {"id": 29, "question": "Pena de morte é justificavel, para certos casos", "effects": {"auth": 1}},
    {"id": 30, "question": "Idade é só um numero.", "effects": {"prog": 1}},
    {"id": 31, "question": "Pessoas deveriam venerar quem quer que seja.", "effects": {"prog": 1}},
    {"id": 32, "question": "Nudismo é perfeitamente normal.", "effects": {"prog": 1}},
    {"id": 33, "question": "Só existem 2 géneros.", "effects": {"prog": -1}},
    {"id": 34, "question": "Existe um problema com minorias etnicas", "effects": {"prog": -1}},
    {"id": 35, "question": "Nada impede um negro de ser racista", "effects": {"prog": -1}},
    {"id": 36, "question": "Ação afirmativa é ótima.", "effects": {"prog": 1}},
    {"id": 37, "question": "É natural o homem(sexo masculino) ser perverso.", "effects": {"prog": 1}},
    {"id": 38, "question": "Existe racismo estrutural.", "effects": {"prog": 1}},
    {"id": 39, "question": "Temos que matar o homem branco.", "effects": {"prog": 1}},
    {"id": 40, "question": "Um embrião não é um ser vivo, por isso pode ser descartável.", "effects": {"prog": 1}},
    {"id": 41, "question": "O aborto deve ser apenas legal em caso de gravidez etópica.", "effects": {"prog": -1}},
    {"id": 42, "question": "Homossexuais, não devem ter o direito a casar.", "effects": {"prog": -1}},
    {"id": 43, "question": "Disforia de género é uma doença mental.", "effects": {"prog": -1}},
    {"id": 44, "question": "Narcóticos, devem ser ilegalizados.", "effects": {"prog": -1}},
    {"id": 45, "question": "Pais devem ter controlo total sobre os seus filhos.", "effects": {"prog": -1}}
];